config/routes.rb
Rails.application.routes.draw do
  # get 'user_session/new'
  # get 'user_session/create'
  # get 'user_session/destroy'

  # resources :users

  constraints subdomain: 'admin' do
    scope as: :admin, module: :admin do
      resources :articles
      root 'articles#index'
    end
    resources :users

    controller :user_session do
      get    'login'  => :new
      post   'login'  => :create
      delete 'logout' => :destroy
    end
    # get '/', to: 'users#index', constraints: { subdomain: 'admin' }

    namespace :upload do
      resources :images, only: [:create, :destroy]
    end
  end

  constraints subdomain: 'api' do
    scope as: :api, module: :api do
      resources :articles, only: [:index, :show]
    end
  end

  resources :articles, only: [:index, :show]


  get '/', to: 'articles#index', constraints: { subdomain: 'www' }
  root 'articles#index', as: 'articles_index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord

  enum category: {
    '傳承簡介'      => 0,
    '世界心精華寶'  => 1,
    '中心佈告欄'    => 2,
    '活動錦集'      => 3,
    '妙義教授'      => 4,
    '佛學問答'      => 5,
  }

  mount_uploader :thumbnail, ImageUploader

  belongs_to :user

  validates :title, :content, :category, presence: true

  before_validation :set_thumbnail

  private

    def set_thumbnail
      doc = Nokogiri::HTML content
      # https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Upload-files-from-a-remote-location-to-JSONB-or-Array-image-column
      if doc.xpath('//img').any?
        self.remote_thumbnail_url = doc.xpath('//img')[0].attr :src
      else
        self.remove_thumbnail!
      end
    end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if params[:category].blank?
      # n + 1 queries https://ihower.tw/rails/performance.html
      @articles = Article.includes(:user).order(id: :desc)
    else
      @articles = Article.includes(:user).where(category: params[:category]).order(id: :desc)
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = User.find_by(params[:user_id])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :category, :content)
    end
end

app/controllers/api/articles_controller.rb
class API::ArticlesController < ApplicationController
  skip_before_action :authorize, only: [:index, :show]

  def index
    @articles = Article.order(id: :desc)
    render json: @articles.as_json(include: { user: { only: :name } })
  end
end

app/controllers/articles_controller.rb
class ArticlesController < WebController
  skip_before_action :authorize, only: [:index, :show]

  # GET /articles
  # GET /articles.json
  def index
    if params[:category].blank?
      # n + 1 queries https://ihower.tw/rails/performance.html
      @articles = Article.includes(:user).order(id: :desc)
    else
      @articles = Article.includes(:user).where(category: params[:category]).order(id: :desc)
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/api/articles_helper.rb
module API::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :標題 %>
    <%= form.text_field :title, id: :article_title, class: 'form-control', placeholder: '標題' %>
  </div>

  <div class="field form-group">
    <%= form.label :分類 %>
    <%= form.select :category, Article.categories.keys, { include_blank: '選擇一個分類' }, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :內容 %>
    <%= form.hidden_field :content, id: :article_content %>
    <div id="editor-container">
      <%= raw @article.content %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit :發表, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<% title '編輯' + @article.title %>
<h3>編輯文章</h3>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/index.html.erb
<% title '管理文章' %>
<p id="notice"><%= notice %></p>

<h3 class="pb-3 mb-4 border-bottom">文章列表</h3>

<%= link_to '發表文章', new_admin_article_path %>

<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">名稱</th>
      <th scope="col">發文者</th>
      <th scope="col">內容</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <th scope="row"><%= article.id %></td>
        <td><%= truncate article.title, length: 15 %></td>
        <td><%= article.user.name %></td>
        <td><%= truncate strip_tags(article.content), length: 35 %></td>
        <td>
          <ul class="list-inline m-0 icon">
            <%= link_to article do %>
              <li class="list-inline-item detail"></li>
            <% end %>

            <%= link_to edit_admin_article_path(article) do %>
              <li class="list-inline-item edit"></li>
            <% end %>

            <%= link_to admin_article_path(article), method: :delete,
                data: { confirm: '是否確定要刪除該文章?' } do %>
              <li class="list-inline-item delete"></li>
            <% end %>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/articles/new.html.erb
<% title '發表文章' %>
<h3>發表文章</h3>

<%= render 'form', article: @article %>

<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/show.html.erb
<% title @article.title %>
<p id="notice"><%= notice %></p>

<%= render 'articles/content', admin_mode: true %>