config/routes.rb
Rails.application.routes.draw do
  # get 'user_session/new'
  # get 'user_session/create'
  # get 'user_session/destroy'

  # resources :users

  constraints subdomain: 'admin' do
    scope as: :admin, module: :admin do
      resources :articles
      root 'articles#index'
    end
    resources :users

    controller :user_session do
      get    'login'  => :new
      post   'login'  => :create
      delete 'logout' => :destroy
    end
    # get '/', to: 'users#index', constraints: { subdomain: 'admin' }

    namespace :upload do
      resources :images, only: [:create, :destroy]
    end
  end

  constraints subdomain: 'api' do
    scope as: :api, module: :api do
      resources :articles, only: [:index, :show]
    end
  end

  resources :articles, only: [:index, :show]


  get '/', to: 'articles#index', constraints: { subdomain: 'www' }
  root 'articles#index', as: 'articles_index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles

  validates :name, :account, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :account %>
    <%= form.text_field :account, id: :user_account %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% title '編輯' + @user.name %>
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% title '管理員列表' %>
<p id="notice"><%= notice %></p>

<h3 class="pb-3 mb-4 border-bottom">管理員</h3>

<% if admin? %>
  <%= link_to '新增管理員', new_user_path %>
<% end %>

<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">名稱</th>
      <th scope="col">帳號</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.account %></td>
        <td>
          <ul class="list-inline m-0 icon">
            <%= link_to user do %>
              <li class="list-inline-item detail"></li>
            <% end %>

            <%= link_to edit_user_path(user) do %>
              <li class="list-inline-item edit"></li>
            <% end %>

            <%= link_to user_path(user), method: :delete,
                data: { confirm: '是否確定要刪除該文章?' } do %>
              <li class="list-inline-item delete"></li>
            <% end %>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<% title '新增管理員' %>
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% title @user.name %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>