config/routes.rb
Rails.application.routes.draw do
  # get 'user_session/new'
  # get 'user_session/create'
  # get 'user_session/destroy'

  # resources :users

  constraints subdomain: 'admin' do
    scope as: :admin, module: :admin do
      resources :articles
      root 'articles#index'
    end
    resources :users

    controller :user_session do
      get    'login'  => :new
      post   'login'  => :create
      delete 'logout' => :destroy
    end
    # get '/', to: 'users#index', constraints: { subdomain: 'admin' }

    namespace :upload do
      resources :images, only: [:create, :destroy]
    end
  end

  constraints subdomain: 'api' do
    scope as: :api, module: :api do
      resources :articles, only: [:index, :show]
    end
  end

  resources :articles, only: [:index, :show]


  get '/', to: 'articles#index', constraints: { subdomain: 'www' }
  root 'articles#index', as: 'articles_index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  enum category: {
    '傳承簡介'      => 0,
    '世界心精華寶'  => 1,
    '中心佈告欄'    => 2,
    '活動錦集'      => 3,
    '妙義教授'      => 4,
    '佛學問答'      => 5,
  }

  mount_uploader :thumbnail, ImageUploader

  belongs_to :user

  validates :title, :content, :category, presence: true

  before_validation :set_thumbnail

  private

    def set_thumbnail
      doc = Nokogiri::HTML content
      # https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Upload-files-from-a-remote-location-to-JSONB-or-Array-image-column
      if doc.xpath('//img').any?
        self.remote_thumbnail_url = doc.xpath('//img')[0].attr :src
      else
        self.remove_thumbnail!
      end
    end
end

app/models/upload.rb
module Upload
  def self.table_name_prefix
    'upload_'
  end
end

app/models/upload/image.rb
class Upload::Image < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles

  validates :name, :account, presence: true, uniqueness: true
  has_secure_password
end

app/models/user_session.rb
# class UserSession
#   def initialize(controller)
#     @controller = controller
#   end
# end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
end

app/controllers/api/articles_controller.rb
class API::ArticlesController < ApplicationController
  skip_before_action :authorize, only: [:index, :show]

  def index
    @articles = Article.order(id: :desc)
    render json: @articles.as_json(include: { user: { only: :name } })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authorize
  # around_action :with_locale
  around_action :with_time_zone


  protected
    def authorize
      unless User.find_by(id: session[:user_id])
        redirect_to login_url, notice: '請先登入'
      end
    end

    # def with_locale
    #   I18n.with_locale('zh-TW') { yield }
    # end

    def with_time_zone
      Time.use_zone('Asia/Taipei') { yield }
    end
end

app/controllers/articles_controller.rb
class ArticlesController < WebController
  skip_before_action :authorize, only: [:index, :show]

  # GET /articles
  # GET /articles.json
  def index
    if params[:category].blank?
      # n + 1 queries https://ihower.tw/rails/performance.html
      @articles = Article.includes(:user).order(id: :desc)
    else
      @articles = Article.includes(:user).where(category: params[:category]).order(id: :desc)
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/user_session_controller.rb
class UserSessionController < AdminController
  skip_before_action :authorize

  def new
  end

  def create
    user = User.find_by(account: params[:account])
    if user.try(:authenticate, params[:password])
      session[:user_id] = user.id
      redirect_to articles_index_url
    else
      redirect_to login_url, alert: '帳號密碼錯誤'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to articles_index_url, notice: '已經登出'
  end
end

app/controllers/users_controller.rb
class UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :admin)
    end
end

app/controllers/web_controller.rb
class WebController < ApplicationController
  layout "web"
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/api/articles_helper.rb
module API::ArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/upload/images_helper.rb
module Upload::ImagesHelper
end

app/helpers/user_session_helper.rb
module UserSessionHelper
  def user_logged_in?
    if session[:user_id]
      true
    else
      false
    end
  end

  def admin?
    user = User.find(session[:user_id])
    user.admin
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_head_tag.html.erb
<%# <title>仰桑貝瑪貴</title> %>
<%= display_meta_tags site: '仰桑貝瑪貴' %>

<%= csrf_meta_tags %>
<%= display_meta_tags charset: 'utf-8' %>
<%# 以下兩種設定都可以防止使用者做畫面縮放，將畫面鎖在縮放比例 100% %>
<%# https://github.com/twbs/bootlint/wiki/W003 %>
<meta name="viewport" content="width=device-width, initial-scale=1">

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head_tag' %>
    <%= display_meta_tags noindex: true, nofollow: true %>
  </head>

  <body>
    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <%= link_to '仰桑貝瑪貴', articles_index_path, class: 'col-md-6' %>
          <% if user_logged_in? %>
            <div>
            <%= link_to '登出', logout_path, method: :delete %>
            </div>
          <% else %>
            <%= link_to '登入', login_path %>
          <% end %>
        </div>
      </header>

      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <%= link_to '文章', articles_path, class: 'p-2 text-muted' %>
          <%= link_to '使用者', users_path, class: 'p-2 text-muted' %>
          <%= link_to '樣板', articles_path, class: 'p-2 text-muted' %>
          <%= link_to '樣板', articles_path, class: 'p-2 text-muted' %>
        </nav>
      </div>

    <main class='container'>
      <%= yield %>
    </main>

    <footer class="blog-footer">
      <%= link_to '回到頂部', articles_index_path %>
    </footer>
  </body>
</html>

app/views/layouts/web.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head_tag' %>
  </head>

  <body>
    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <%= link_to '仰桑貝瑪貴', articles_index_path, class: 'col-md-6' %>
        </div>
      </header>

      <% if false %>
      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <%= link_to '樣板', articles_path, class: 'p-2 text-muted' %>
          <%= link_to '樣板', articles_path, class: 'p-2 text-muted' %>
          <%= link_to '樣板', articles_path, class: 'p-2 text-muted' %>
          <%= link_to '樣板', articles_path, class: 'p-2 text-muted' %>
        </nav>
      </div>
      <% end %>

      <%# commment start %>
      <% if false %>
        <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
          <div class="col-md-6 px-0">
            <h1>祖古&nbsp&nbsp貝瑪仁增仁波切</h1>
            <p>出生於貝瑪貴蓮花莊聖境，許多成就者與瑜珈母皆認證其為札昂林猛咒洲尊者乘願轉世祖古。</p>
            <p>為能宏揚顯密教法，貝瑪仁增 仁波切自三十二歲開始順應因緣遊化各地並應卓千佛學會之邀來到台灣，盡力傳授顯密法教。</p>
            <p>目前為台北虛空法林佛學會住持上師。</p>
          </div>
        </div>
      <% end %>
      <%# comment end %>

      <div>
        <%= image_tag '247309_resize.jpg', class: 'img-fluid' %>
      </div>
    </div>

    <main class='container'>
      <%= yield %>
    </main>

    <footer class="blog-footer">
      <%= link_to '回到頂部', articles_index_path %>
    </footer>
  </body>
</html>